public class Exceptions {
    public static void main(String[] args) throws MyBeautifulException {
        ///something hppens here in this method.
        //and it occured an error which is MyBeautifulException
        //throw new MyBeautifulException("There is a specific problem.");

        //String name = "Emrecan";

        /*
        try {
            int a = 10;
            int b = 0;
            int c = a / b;
        }catch (ArithmeticException e){
            System.out.println(e);
        } finally{
            System.out.println("Thats finally");
        }
         */

    }
}